# Assignment 5 Solution


## 1. Palindrome detector: 

Ask the user for a word and print ’True’ if it is a palindrome, otherwise, print
’False’.(A palindrome is a string that reads the same forwards and backwards.) Make sure to take care
of user inconsistencies. e.g. trailing or leading white spaces shouldn’t make your program fail to detect
the palindrome. Same with inconsistent capitalization or if the word has a mixture of upper or lower
case letters. i.e if a user enters civic, CIvIC, cIVIc your program should print true

In [1]:
# get user input
word = input("Please enter palindromatic word:").casefold() # casefold it to avoid case inconsistencies
word = word.strip() # strip both trailing and leading whitespace
print(word == word[::-1]) # reverse the word and compare it to the original

Please enter palindromatic word: civIC


True


## 2. Password generator: 

Sometimes, when you create a new account online, google suggests a strong
random password for your account. Let’s recreate that functionality! Write a program that asks the user
for the length of password that the user desires. Then, generate a random password of the desired length
with a mix of uppercase and lowercase letters, numbers and special characters. Print the password.

In [2]:
import random # import random library to access its functions

password_length = int(input("Enter password length:")) # get input from user and cast it into an int
character_pool = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz012345789~!@#$%^&*()-=]|\/.,'

# Now sample the password from the string
password = "".join(random.sample(character_pool, password_length)) # join to create a string from the result of sampling (which is a list)

print(f"Your new password is: {password}")

Enter password length: 20


Your new password is: X4)KNt9yd\.g@1iU=o$T


## 3. Century age calculator: 

Write a program that asks the user for their name and their age. Then print out
a message addressing them by their name and telling them the year that they will turn 100 years old. e.g
If Messi (who’s 36 years old) ran your program, it would print out: ” Hello Messi! You will turn 100 in
the year 2087!”

In [3]:
# get user input
name = input("Your name please:")
age = int(input("Your age please:"))
print(f"Hello {name}! You will turn 100 in the year {2023 - age + 100}")

Your name please: Messi
Your age please: 36


Hello Messi! You will turn 100 in the year 2087


## 4
print the following statement verbatim using raw strings and/or f string formatting:
````verbatim
"The world is round", said the quick brown fox, ’and the
ocean is blue’, said the lazy dog.
````

In [4]:
my_string = ''' "The world is round", said the quick brown fox, 'and the
ocean is blue', said the lazy dog.'''
print(my_string)

 "The world is round", said the quick brown fox, 'and the
ocean is blue', said the lazy dog.


## 5 Divider


In [5]:
# division with formatted printing
num1 = float(input("Enter the numerator:"))
num2 = float(input("Enter the denominator:"))
print(f"{num1} {chr(247)} {num2} = {num1/num2:+.2f}") # chr() and ord() are opposites. character <-> integer and vice versa

Enter the numerator: 88
Enter the denominator: 22.3


88.0 ÷ 22.3 = +3.95


## Dot Product Calculator: 

The dot product of two matrices combines the two matrices (not necessarily
of the same dimension) into a third matrix. It involves taking the sum of the product of corresponding
elements from the rows of the first matrix and the columns of the second matrix.
The dot product is useful for operations in deep learning, optimization among other topics.

Assuming that we represent matrices as nested lists, e.g.
matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]


Write a program that calculates the dot product of any two matrices whose dimensions agree, and prints
out the result. Confirm that your program can handle matrices that are not square matrices e.g does it
compute the dot product of a 5 by 2 matrix and a 2 by 3 matrix? (this would result in a 5 by 3 matrix)

In [21]:
matrix1 = [[1,2,3,4,5],[6,7,8,9,10]] # 2 by 5
matrix2 = [[11,12],[13,14],[15,16],[17,18],[19,20]] # 5 by 2
# we expect the result to be a 2 by 2 matrix

# generate an empty matrix to hold the dot product
# recall, the new matrix has the same number of columns as the matrix on the left 
# and same number of rows as the matrix on the right
dot = []
for _ in range(len(matrix1)): #rows of left hand side matrix
    row = []
    for _ in range(len(matrix2[0])): # columns of RH matrix
        row.append(0)
    dot.append(row)
print (f"empty result matrix: {dot}")
        

for i in range(len(matrix1)): #rows of left hand side matrix
    for j in range(len(matrix2[0])): # Iterate over columns of the second matrix
        for k in range(len(matrix2)):
            dot[i][j] += matrix1[i][k] * matrix2[k][j]
print(dot)

empty result matrix: [[0, 0], [0, 0]]
[[245, 260], [620, 660]]


In [7]:
# sanity check with numpy
import numpy as np
m1 = np.matrix(matrix1)
m2 = np.matrix(matrix2)
print(m1.dot(m2))

[[245 260]
 [620 660]]


In [8]:
# test the solution with a square matrix
# square matrix
matrix1 = [[1,2,3],[4,5,6],[7,8,9]] # 3 by 3
matrix2 = [[10,11,12],[13,14,15],[16,17,18]] # 3 by 3

# we expect the result to be a 3 by 3 matrix

# generate an empty matrix to hold the dot product
# recall, the new matrix has the same number of columns as the matrix on the left 
# and same number of rows as the matrix on the right
dot = []
for _ in range(len(matrix1)): #rows of left hand side matrix
    row = []
    for _ in range(len(matrix2[0])): # columns of RH matrix
        row.append(0)
    dot.append(row)
print (dot)

for i in range(len(matrix1)): #rows of left hand side matrix
    for j in range(len(matrix2[0])): # Iterate over columns of the second matrix
        for k in range(len(matrix2)):
            dot[i][j] += matrix1[i][k] * matrix2[k][j]
print(dot)

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]
[[84, 90, 96], [201, 216, 231], [318, 342, 366]]


In [9]:
m1 = np.matrix(matrix1)
m2 = np.matrix(matrix2)
print(m1.dot(m2))

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [10]:
# A (step-by-step) walkthrough of a solution to the dot product


# the goal is to get the columns of the second matrix and multiply them with the rows of the first matrix
# for example, given two square matrices:
# matrix1 = [[1,2,3],[4,5,6],[7,8,9]] # 3 by 3
# matrix2 = [[10,11,12],[13,14,15],[16,17,18]] # 3 by 3

# we see that we can easily get the rows of the first matrix by iterating through the list
# matrix1[0] gives you the first row, matrix1[1] gives you the second row and so on and so forth
# but extracting the columns of the second matrix is not straightfoward because of how we're representing the matrix
# We need to manipulate things a little to get the desired form

# to get the first column, we need to get the first element of the nested lists e.g. 
# if matrix2 = [[10,11,12],[13,14,15],[16,17,18]], we need to get 10, 13, and 16 to form the first column
# in python, we can do it this way:
matrix2 = [[10,11,12],[13,14,15],[16,17,18]]
col1 = []
for row in matrix2:
    col1.append(row[0])
print(col1)


[10, 13, 16]


In [11]:
# likewise, to get the second column, we need to get the second element in each of the nested lists as follows
col2 = []
for row in matrix2:
    col2.append(row[1])
print(col2)

[11, 14, 17]


In [12]:
# third column
col3 = []
for row in matrix2:
    col3.append(row[2])
print(col3)

[12, 15, 18]


In [13]:
# so, basically, we have transposed our matrix2!
matrix2_transposed = [col1,col2,col3]
print(f"original matrix:  {matrix2}")
print(f"transposed matrix: {matrix2_transposed}")

original matrix:  [[10, 11, 12], [13, 14, 15], [16, 17, 18]]
transposed matrix: [[10, 13, 16], [11, 14, 17], [12, 15, 18]]


In [14]:
# can we do it in one go using for loops? We want our solution to work for any 2 dimensional matrix size, not just for 3 by 3 matrices
# let's test it with non-square matrices
matrix1 = [[1,2,3,4,5],[6,7,8,9,10]] # 2 by 5
matrix2 = [[11,12],[13,14],[15,16],[17,18],[19,20]] # 5 by 2
matrix2_transposed = [] # note, this overwrites the matrix2_transposed that we created manually in the previous cell
#if matrix2 is of size n by m, the size of the transposed matrix is going to be m by n
n = len(matrix2)
m = len(matrix2[0]) # length of any of the internal lists gives us the number of columns

# create an empty transposed matrix:
for i in range(m):
    row = []
    for j in range(n):
        row.append(0)
    matrix2_transposed.append(row)
print(matrix2_transposed)



[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


In [15]:
# you'll notice that this is very similar to the operation that we need to do! 
# i.e we want to fill matrix2_transposed rows with the column values of matrix2 (instead of with zeros)
# remember how the columns correspond to the rows?

# from this comment : 
# to get the first column: we need to get the first element of the nested lists e.g. 
# if matrix2 = [[10,11,12],[13,14,15],[16,17,18]], we need to get 10, 13, and 14 to form the first column
            
# transpose
for i in range(len(matrix2)):
    for j in range(len(matrix2[0])):
        matrix2_transposed[j][i] = matrix2[i][j] # basically swapping the row and column indeces
print(matrix2_transposed)            

print(f"matrix1: {matrix1}")
print(f"original matrix2:  {matrix2}")
print(f"transposed matrix2: {matrix2_transposed}")

[[11, 13, 15, 17, 19], [12, 14, 16, 18, 20]]
matrix1: [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
original matrix2:  [[11, 12], [13, 14], [15, 16], [17, 18], [19, 20]]
transposed matrix2: [[11, 13, 15, 17, 19], [12, 14, 16, 18, 20]]


In [16]:
# first , let's do a sanity check and confirm that our dot product works before assigning it to the empty result matrix
for row in matrix1:
    for column in matrix2_transposed:  
        total = 0
        for r,c in zip(row,column): # r is row in matrix1, and c is column in matrix2
            total += r*c
        print(total)

245
260
620
660


In [17]:
# now that we have transposed the matrix, and confirmed that our multiplication operation works...
#...we can perform the actual multiplication for the dot product while assigning it to our empty result matrix

# We can use the loop structure that we developed above to iterate through the matrices

# let's create an empty matrix to hold the values of the resulting dot product
# it'll be of size len(matrix1) and len(matrix2[0])
dot_matrix = []
for i in range (len(matrix1)):
    row = []
    for j in range(len(matrix2[0])):
        row.append(0)
    dot_matrix.append(row)
print(dot_matrix)

[[0, 0], [0, 0]]


In [18]:
# Now, we just need to assign the sums to our empty dot_matrix and we're done!
# Our main challenge here is to figure out how the sums get stored in the results matrix
result_matrix = []
for row in matrix1:
    result_row = []
    for column in matrix2_transposed:  
        total = 0
        for r,c in zip(row,column): # r is row in matrix1, and c is column in matrix2
            total += r*c
        print(total)
        result_row.append(total)
    result_matrix.append(result_row)
print(result_matrix)


245
260
620
660
[[245, 260], [620, 660]]


In [19]:
# The solution in full:
# combining all the parts into one cell

# # uncomment these to test with square matrices
matrix1 = [[1,2,3],[4,5,6],[7,8,9]] # 3 by 3
matrix2 = [[10,11,12],[13,14,15],[16,17,18]] # 3 by 3

# uncomment to test with non-square matrices
# matrix1 = [[1,2,3,4,5],[6,7,8,9,10]] # 2 by 5
# matrix2 = [[11,12],[13,14],[15,16],[17,18],[19,20]] # 5 by 2

# create empty matrix to hold the transpose of matrix2
#if matrix2 is of size n by m, the size of the transposed matrix is going to be m by n
n = len(matrix2)
m = len(matrix2[0]) # length of any of the internal lists gives us the number of columns

# create an empty transposed matrix:
matrix2_transposed = []
for i in range(m):
    row = []
    for j in range(n):
        row.append(0)
    matrix2_transposed.append(row)

# transpose matrix2
for i in range(len(matrix2)):
    for j in range(len(matrix2[0])):
        matrix2_transposed[j][i] = matrix2[i][j] # basically swapping the row and column indeces
# print(matrix2_transposed)     


# perform the multiplication and assignment to result matrix
result_matrix = []
for row in matrix1:
    result_row = []
    for column in matrix2_transposed:  
        total = 0
        for r,c in zip(row,column): # r is row in matrix1, and c is column in matrix2
            total += r*c
        result_row.append(total)
    result_matrix.append(result_row)
print(f'solution: {result_matrix}')


solution: [[84, 90, 96], [201, 216, 231], [318, 342, 366]]


## The doctors

Use a for loop to append the letters “Dr.” in front of each name in the following list: [”Phil”, ”Oz”, ”Seuss”,
”Dre”, ”Johnsen”, ”Morelock”] . Save the prefixed names in a new list called updated docs. updated docs
should be: [”Dr.Phil”, ”Dr.Oz”, ”Dr.Seuss”, ”Dr.Dre”, ”Dr.Johnsen”, ”Dr.Morelock”]

In [20]:
docs = ['Phil', 'Oz', 'Seuss','Dre', 'Johnsen', 'Morelock']
updated_docs = []
for doctor in docs:
    updated_docs.append("Dr. " + doctor)
print(updated_docs)

['Dr. Phil', 'Dr. Oz', 'Dr. Seuss', 'Dr. Dre', 'Dr. Johnsen', 'Dr. Morelock']
