### Exercise 6a Template - RNN implementation ###

In [1]:
'''Import libraries'''
import numpy as np # import numpy library as np

In [2]:
# Initialising the Variables

n_features = 10 # Input which has 10 features (like the numeric representation of a word - word embedding)
n_hidden_units = 4 # 4 neurons

# Number of predicted outputs (y_t)
n_output_units = 5  # for example, 5 classes in a classification problem

# Random initialization for the sake of example
np.random.seed(42)

# Input, Weights, Bias
x_t = np.random.randn(n_features) # Random input vector
h_prev = np.random.randn(n_hidden_units) # Random hidden state vector
Wx = np.random.randn(n_hidden_units, n_features) # Random weights for the input x
Wh = np.random.randn(n_hidden_units, n_hidden_units) # Random weights for the previous state
Wy = np.random.randn(n_output_units, n_hidden_units) # Random weights for the prediction y
b = np.random.randn(n_hidden_units) # Random bias
by = np.random.randn(n_output_units) # Random bias for the predicted output

print(f"Previous state input weights:\n {Wh}\n\n Weights for thw input x:\n{Wx}\n\nWeights for the prediction y:\n{Wy}\n\nBias:\n{b}\nBias for predicted output{Wy}")
print(f"\n\nShape of Wa: {Wh.shape}, of Wx{Wx.shape}, of Wy: {Wy.shape}, bias: {b.shape}, predicted output bias: {by.shape}")

Previous state input weights:
 [[ 1.03099952  0.93128012 -0.83921752 -0.30921238]
 [ 0.33126343  0.97554513 -0.47917424 -0.18565898]
 [-1.10633497 -1.19620662  0.81252582  1.35624003]
 [-0.07201012  1.0035329   0.36163603 -0.64511975]]

 Weights for thw input x:
[[-1.72491783 -0.56228753 -1.01283112  0.31424733 -0.90802408 -1.4123037
   1.46564877 -0.2257763   0.0675282  -1.42474819]
 [-0.54438272  0.11092259 -1.15099358  0.37569802 -0.60063869 -0.29169375
  -0.60170661  1.85227818 -0.01349722 -1.05771093]
 [ 0.82254491 -1.22084365  0.2088636  -1.95967012 -1.32818605  0.19686124
   0.73846658  0.17136828 -0.11564828 -0.3011037 ]
 [-1.47852199 -0.71984421 -0.46063877  1.05712223  0.34361829 -1.76304016
   0.32408397 -0.38508228 -0.676922    0.61167629]]

Weights for the prediction y:
[[ 0.36139561  1.53803657 -0.03582604  1.56464366]
 [-2.6197451   0.8219025   0.08704707 -0.29900735]
 [ 0.09176078 -1.98756891 -0.21967189  0.35711257]
 [ 1.47789404 -0.51827022 -0.8084936  -0.50175704]
 [

In [7]:
# Softmax function is given - understand what it does
# It ultimately converts outputs to probability values

def softmax(z): # z is the input vector
    t = np.exp(z) # take the exponential of the input vector
    a = np.exp(z) / np.sum(t, axis=1).reshape(-1,1) # divide the exponential of the input vector by the reshaped sum of the exponential of the input vector
    return a # return the softmax of the input vector

In [4]:
# Write a function to take the inputs as previous state,x and bias values to return the value of the next state using the RNN equation
# Always check the dimensions of your results

# RNN Basic function

# TODO 

'''A RNN cell gets 2 inputs - One from the previous timestep output (a^(t-1)) and One the current timestep input (x^t) with their wieghts'''
def rnn_step(x_t, h_prev, Wx, Wh, b):
    """
    Perform a single RNN step.

    Arguments:
    x_t -- Current input data for timestep t, numpy array of shape (n_features,)
    h_prev -- Previous hidden state, numpy array of shape (n_hidden_units,)
    Wx -- Weight matrix multiplying the input, numpy array of shape (n_hidden_units, n_features)
    Wh -- Weight matrix multiplying the hidden state, numpy array of shape (n_hidden_units, n_hidden_units)
    b -- Bias vector, numpy array of shape (n_hidden_units,)

    Returns:
    h_next -- Next hidden state, numpy array of shape (n_hidden_units,)
    """
    # Compute the next hidden state
    
    #TODO

    a_prev = h_prev # previous timestep input (hidden state)
    W_aa = Wh # weight of previous timestep input (hidden state)
    x_t = x_t # current timestep input
    W_ax = Wx # weight of current timestep input
    b_a = b # bias

        
    '''Their respective  dot products are taken, and the two inputs are added together with the bias (as per equation for a<t>.)'''
    a_t = np.tanh(np.dot(Wx, x_t) + np.dot(Wh, h_prev) + b)

    return a_t
        
    # END TODO

In [5]:
# Compute next state using the RNN equation developed in the function
# print the values and the shape
# make sure the shape (dimension of output is what it should be. In this case (4,1)

# TO DO
'''They are then fed to a tanh activation function to get the output a<t> which goes as input to the next time step.'''
x_t = x_t # reshape the input
a_prev = h_prev # reshape the previous timestep input (hidden state)
W_ax = Wx # weight of current timestep input
W_aa = Wh # weight of previous timestep input (hidden state)
b_a = b # bias

a_t = rnn_step(x_t, a_prev, W_ax, W_aa, b) # get the next hidden state

print(f"Next hidden state (a_next): {a_t}")
print("Shape of a_next:", a_t.shape)

# END TODO

Next hidden state (a_next): [ 0.46019631  0.2484162  -0.99331655  0.98477645]
Shape of a_next: (4,)


In [9]:
# Compute the prediction for the particular cell, which is y(t)
# Use the provided softmax function
# Feed the softmax the value of y_t but make sure it has a shape (5,1) and not just (5,)
# Print the output as the probabilites of number of classification classes
# Since the classes are 5 the output dimension should be the same.

y_t = np.dot(Wy, a_t) + by

y_probailities_of_classes = softmax(y_t.reshape(-1,1)) # Reshaping is done to make sure the array being fed is (n,1)

print(f"The predicted output y:\n{y_t}")
print(f"Predicted prbabilites of classes for this RNN Cell:\n{y_probailities_of_classes}\nShape: {y_probailities_of_classes.shape}")

The predicted output y:
[ 1.73268879 -2.84585877  0.41448371  1.1214015   1.53971849]
Predicted prbabilites of classes for this RNN Cell:
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
Shape: (5, 1)
