In [3]:
# Create a function
import numpy as np
def roll_die():
    return np.random.randint(1,7) # Give a number between 1 and 6

In [4]:
roll_die()

5

In [5]:
# Take in an input value
import numpy as np
def roll_dice(num_dice):
    return np.random.randint(1,7,num_dice) # Give a number between 1 and 6

In [6]:
roll_dice(5)

array([2, 4, 3, 2, 1])

In [12]:
# Give a number between 1 and sides
import numpy as np
def roll_dice(num_dice, sides):
    return np.random.randint(1,sides+1,num_dice)

In [13]:
roll_dice(2,60)

array([57, 27])

In [16]:
# Another way to call Python functions and out of order
roll_dice(sides=6,num_dice=7)

array([4, 1, 6, 3, 3, 5, 2])

In [17]:
# Provide default inputs
import numpy as np
def roll_dice(num_dice=2, sides=6):
    return np.random.randint(1,sides+1,num_dice)

In [18]:
roll_dice()

array([5, 2])

In [19]:
roll_dice(5)

array([1, 1, 6, 6, 3])

In [20]:
roll_dice(sides=2)

array([1, 2])

In [21]:
# Specify the expected input and expected output so the editor can provide context when unclear
import numpy as np
def roll_dice(num_dice:int=2,sides:int=6)->np.array:
    return np.random.randint(1,sides+1,num_dice)

In [22]:
roll_dice(6,2)

array([2, 1, 2, 1, 1, 1])

In [23]:
roll_dice

<function __main__.roll_dice(num_dice: int = 2, sides: int = 6) -> <built-in function array>>

In [25]:
# Functions are objects
a = roll_dice
a(6,2)

array([1, 2, 2, 2, 1, 2])

In [26]:
numbers = roll_dice(6,6)
numbers

array([2, 2, 4, 4, 1, 1])

In [27]:
# Roll dice is applied to each of the numbers in 'numbers'
mapped = list(map(roll_dice,numbers))
print(mapped)

[array([2, 2]), array([4, 3]), array([2, 3, 4, 2]), array([3, 5, 3, 3]), array([3]), array([3])]


In [30]:
# We can implement our own map function
def my_map(function_to_map,list_to_map):
    to_return=[]
    for n in list_to_map:
        to_return.append(function_to_map(n))
    return to_return

In [31]:
my_map(roll_dice,numbers)

[array([6, 5]),
 array([2, 4]),
 array([5, 5, 5, 3]),
 array([6, 3, 3, 4]),
 array([3]),
 array([3])]

In [32]:
def clip_first(l:list):
    del l[0]

In [33]:
a_list = [1,2,3]
clip_first(a_list)
print(a_list)

[2, 3]


In [34]:
# Values are passed into the function so changes are saved
clip_first(a_list)
print(a_list)

[3]


In [38]:
A = 3
B = 4
def my_fun(A):
    A = 4 # this is the A in the function definition
    B = 7 # this is a different b that is local to my_fun
    print(A)
    print(B)

In [40]:
print(A)
print(my_fun(A))

3
4
7
None


In [41]:
print(B)

4


In [42]:
# We can refer to a variable name outside the function
# This is not recomended
A = 3
def my_fun():
    print(A)
my_fun()

3


In [44]:
# If you want to reassign the A outside of the function
# Considered pretty bad pactice
A = 3
def my_fun():
    global A
    A = 4
my_fun()
print(A)

4
