### Exercise 5 Solution

In [1]:
import numpy as np

#### Generate Data 

In [2]:
# Initialize inputs values.

X = np.array([[2,1]])
W = np.array([[0.5],[0.5]])
b = np.array([0.5])

print(f"Shapes of X, W and b:{X.shape, W.shape,b.shape}")

Shapes of X, W and b:((1, 2), (2, 1), (1,))


In [3]:
# New data

X1 = np.array([1,5,2,6,3,7,4,8,1,0]).reshape(5,2)
print(f"Shape of X: {X1.shape} and X:\n{X1}")

Shape of X: (5, 2) and X:
[[1 5]
 [2 6]
 [3 7]
 [4 8]
 [1 0]]


#### NN Class ####

In [4]:
class Neuron:
    def __init__(self,W,X,b):
        self.W = W
        self.X = X
        self.b = b
        
    def summation(self):
        return np.dot(self.X,self.W) + self.b
    
    def sigmoid(self):
        return 1/(1 + np.exp(-self.summation()))
    
    def print_values(self):
        print(f"Weights:\n{self.W}\n\nBias: {b}")

In [5]:
# Instantiate  objects

neuron1 = Neuron(W,X,b)
neuron2 = Neuron(W,X1,b)


In [6]:
# neuron 1 output

print(f"Summation: {neuron1.summation()}")
print(f"Activation Output: {neuron1.sigmoid()}\n")

# Weights and bias
neuron1.print_values()

Summation: [[2.]]
Activation Output: [[0.88079708]]

Weights:
[[0.5]
 [0.5]]

Bias: [0.5]


In [9]:
# neuron 2 output

print(f"Summation:\n{neuron2.summation()}\n")
print(f"Activation Output:\n{neuron2.sigmoid()}\n")

# Weights and bias
neuron2.print_values()

Summation:
[[3.5]
 [4.5]
 [5.5]
 [6.5]
 [1. ]]

Activation Output:
[[0.97068777]
 [0.98901306]
 [0.99592986]
 [0.99849882]
 [0.73105858]]

Weights:
[[0.5]
 [0.5]]

Bias: [0.5]
