In [1]:
import numpy as np

In [2]:
'''Write a “Python Class” with “methods” to completely represent a simple Nural Network.'''
class NN:
    def __init__(self, W, b): # constructor where W is the weights, b is the bias
        self.W = W # W is a matrix of weights
        self.b = b  # b is a vector of biases

    def compute_z(self, X): # X is the input
        return np.dot(X, self.W.T) + self.b # z = transpose(W)*X + b

    def sigmoid(self, z): # compute the activation function, which is the sigmoid function
        return 1 / (1 + np.exp(-z)) # sigmoid function

    def predict(self, X): # perform the sigmoid calculations all together in one function
        z = self.compute_z(X) # compute z
        h_w = self.sigmoid(z) # Sigmoid computation with computed z
        return h_w  # returning value of activation ‘a’ as ‘hw’

    def print_weights_bias(self): # print the weights and bias
        print("Weights:\n", self.W) # print the weights
        print("Bias:\n", self.b) # print the bias


In [3]:
'''Test the Simple Neural Network Class'''
# Define the given values
X = np.array([[2, 1]]) # input
W = np.array([[0.5, 0.5]]) # weights
b = np.array([[0.5]]) # bias

# Create an instance of the class
nn = NN(W, b) # create an instance of the class

# Compute and print the results
z = nn.compute_z(X) # compute z
h_w = nn.predict(X) # compute the sigmoid function

print("Computed z:", z) # print the computed z
print("Computed h_w:", h_w) # print the computed hw
nn.print_weights_bias() # print the weights and bias

Computed z: [[2.]]
Computed h_w: [[0.88079708]]
Weights:
 [[0.5 0.5]]
Bias:
 [[0.5]]


In [4]:
'''Create an X matrix of shape (5, 2) with arbitrary values'''
X = np.array([1,5,2,6,3,7,4,8,1,0]).reshape(5,2)
W = np.array([[0.5, 0.5]]) # weights
b = np.array([[0.5]]) # bias

# Create an instance of the class
nn = NN(W, b) # create an instance of the class

# Compute and print the results
z = nn.compute_z(X) # compute z
h_w = nn.predict(X) # compute the sigmoid function

print(f"Computed z:\n", z) # print the computed z
print(f"Computed h_w should be a (5,1) matrix:\n", h_w) # print the computed hw
nn.print_weights_bias() # print the weights and bias

Computed z:
 [[3.5]
 [4.5]
 [5.5]
 [6.5]
 [1. ]]
Computed h_w should be a (5,1) matrix:
 [[0.97068777]
 [0.98901306]
 [0.99592986]
 [0.99849882]
 [0.73105858]]
Weights:
 [[0.5 0.5]]
Bias:
 [[0.5]]
